// frontend/fretquiz/src/Navbar.svelte
<nav>
  <ul>
    <li>
      <a href="/">Home</a>
    </li>
    <li>
      <a href="/login">Login</a>
    </li>
    <li>
      <a href="/game">Game</a>
    </li>
    <li>
      <a href="/games">Games</a>
    </li>
    <li>
      <a href="/about">About</a>
    </li>
  </ul>
</nav>

<!-- <style>
  li {
    float: left;
  }
</style> -->

// frontend/fretquiz/src/components/Navbar.tsx
import * as React from 'react';
import { Link } from 'react-router-dom';
import './Navbar.css';

export function Navbar() {
  return (
    <div className='Navbar'>
      <nav>
        <ul>
          <li>
            <Link to='/'>Home</Link>
          </li>
          <li>
            <Link to='/login'>Login</Link>
          </li>
          <li>
            <Link to='/game'>Game</Link>
          </li>
          <li>
            <Link to='/games'>Games</Link>
          </li>
        </ul>
      </nav>
    </div>
  );
}
