// frontend/fretquiz/src/game/Fretboard.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { FretboardDiagram } from 'fretboard-diagram';
  import type { ClientGuess, FretCoord } from './types';
  import { sendGuess } from '../websocket/game';
  import { game, user } from '../stores';

  let container: HTMLElement;
  const divId = 'fretboard-div';

  const defaultColor = 'white';
  const correctColor = 'lime';
  const incorrectColor = 'deeppink';

  const handleClick = (gameId: string, playerId: string, clickedFret: FretCoord) => {
    const guess: ClientGuess = { gameId, playerId, clickedFret };
    sendGuess(guess);
  }

  onMount(() => {
    const div = document.createElement('div');
    div.id = divId;
    container.appendChild(div);

    new FretboardDiagram({
      id: divId,
      onClick: (coord: FretCoord) => handleClick($game.id, $user.id, coord)
    });
  });
</script>

<div bind:this={container}/>

// frontend/fretquiz/src/features/game/components/Fretboard.tsx
import * as React from 'react';
import { FretboardDiagram } from 'fretboard-diagram';
import { useSelector } from 'react-redux';
import { selectUserId } from '../../user/userSlice';
import { selectGameId, selectGameState } from '../gameSlice';
import { FretCoord } from '../types';
import { sendGuess } from '../../../websocket/game';

const correctColor = 'lime';
const incorrectColor = 'deeppink';

export function Fretboard() {
  const userId = useSelector(selectUserId);

  const gameId = useSelector(selectGameId);
  const gameState = useSelector(selectGameState);

  React.useEffect(() => {
    const isPlaying = gameState == 'PLAYING';

    // selects the element with the given `id` and draws a fretboard diagram there
    new FretboardDiagram({
      id: 'fretboard-canvas',
      drawDotOnHover: isPlaying,
      onClick: (coord: FretCoord) => {
        if (gameId && isPlaying) {
          const guess = { 
            gameId, 
            playerId: userId, 
            clickedFret: coord 
          };

          sendGuess(guess);
        }
      }
    });
  });

  return (
    <div className="Fretboard">
      <div id="fretboard-canvas" />
    </div>
  )
}
