// frontend/fretquiz/src/game/GameList.svelte
<script lang="ts">
  import { gameIds } from '../stores';
  import { sendJoinGame } from '../websocket/game';
  import { user } from '../stores';
</script>

<h2>Games</h2>
<ul>
  {#each $gameIds as gameId}
    <li on:click={() => sendJoinGame(gameId, $user.id)}>
      {gameId}
    </li>
  {/each}
</ul>

// frontend/fretquiz/src/features/game/GameList.tsx
import * as React from 'react';
import { useSelector } from 'react-redux';
import { sendJoinGame } from '../../websocket/game';
import { selectUserId } from '../user/userSlice';
import { Game, selectGameIds } from './gameSlice';

interface GameLinkProps {
  gameId: string,
  userId: string
}

function GameLink(props: GameLinkProps) {
  const { gameId, userId } = props;

  return (
    <li
      onClick={() => {
        sendJoinGame(userId, gameId);
      }}
    >
      {gameId}
    </li>
  );
}

export function GameList() {
  const gameIds = useSelector(selectGameIds);
  const userId = useSelector(selectUserId);

  return (
    <div className="GameList">
      <h2>Games</h2>
      <ul>
        {
          gameIds.map((gameId, index) => {
            return <GameLink key={index} gameId={gameId} userId={userId} />
          })
        }
      </ul>
    </div>
  );
}
