// frontend/fretquiz/src/game/components/StartGameButton.tsx
import React from 'react';
import { useSelector } from 'react-redux';
import { sendStartGame } from '../../websocket/game';
import { selectGameId } from '../gameSlice';

export function StartGameButton() {
  const gameId = useSelector(selectGameId);

  return (
    <div className="StartGameButton">
      <button onClick={() => gameId && sendStartGame(gameId)}>
        Start Game
      </button>
    </div>
  );
}

// frontend/fretquiz/src/game/StartGameButton.svelte
<script lang="ts">
  import { sendStartGame } from "../websocket/game";
  import { user, game } from "../stores";

  // only send the start request if the user and game are already set
  const onClick = () => $user && $game && sendStartGame($game.id);
</script>

<button on:click={onClick}>
  Start Game
</button>
